language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "Me1bwcYLK+HTwS/S46w0sj6c470tXAu2gAio/QSRNCUZOhdIGL8I66yV1k2ii6hiBCgAdcTCIUka8hCwvPMqq50jusrWP9ztNi/urOU+/ADChqhDqFp8+54aiZ2LJJ2wD1IjUKF832KAxIWYjPRY9wQjZYXvr9Cz8P2pV55Xl+2K1WduvrPH3aGq6HEHX1uxN5VbNSx6skEtnxPzfSbYj5iOcd5MopKfH479ZB9ysf3axenhgcg/8Qf1dMRvo+k1s9LzW9LCNkFbqJQWntQlq2yv37KOFxnZaLAdd34pakxzTk4C47Ry58d7Jr7WOrF4WELMD8Qy+Y0h9uc0RH20gqU7rscMhU+YlOt9Tf5tyCQRI5JXFe7isWHj85XZMf4sjXRscEonQjvevAdHOs0vYnDXUi2m1nZvGuueAysW6A/rcD7OfXF3aKm+B9kCh80TzPJTKcIOKbVS30BhhQqr91xS2FoiOTUpl9JaWBrELmLEfu1sLI4XPgFJ6nNX/jwusi1kqxntk+5fSdCvP8B1Okq7wp3OsBpQ+SSIsIJ72HaGSLmYmIqOh0ejqtHYMAJZacPLGONv+cBwPgGJvvR0EPjBo22Gy2JnkPLmzO7dRsDbFABRNCHZYdSrOWeRNFxGZ8XS/ZcjKuomKDs/pP109G3kwcHErc02uJcKTmiUg4g="
  app: travisci-playground